/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
/**
 *
 * @author Patrik
 */
public class okno1 extends javax.swing.JFrame implements KeyListener, Runnable{
   static int x,y;
   int FPS=60;
boolean threadIsRunning=true;
Thread t1;
    /**
     * Creates new form okno1
     */
    public okno1() {
        initComponents();
        addKeyListener(this);
        t1 = new Thread(this);
        t1.start();
        x=filip.getX();
        y=filip.getY();
    }
    
        public void run() {
        while (threadIsRunning) {
            if (!(filip.getBounds().intersects(jLabel6.getBounds()))){
            if (filip.getBounds().intersects(jLabel1.getBounds())||filip.getBounds().intersects(jLabel2.getBounds())||filip.getBounds().intersects(jLabel3.getBounds())||filip.getBounds().intersects(jLabel5.getBounds())||filip.getBounds().intersects(jLabel3.getBounds())||filip.getBounds().intersects(jLabel4.getBounds())||filip.getBounds().intersects(jLabel5.getBounds())||filip.getBounds().intersects(jLabel6.getBounds())||filip.getBounds().intersects(jLabel7.getBounds())||filip.getBounds().intersects(jLabel8.getBounds())||filip.getBounds().intersects(jLabel9.getBounds())||filip.getBounds().intersects(jLabel10.getBounds())||filip.getBounds().intersects(jLabel11.getBounds())||filip.getBounds().intersects(jLabel12.getBounds())||filip.getBounds().intersects(jLabel13.getBounds())||filip.getBounds().intersects(jLabel14.getBounds())||filip.getBounds().intersects(jLabel15.getBounds())||filip.getBounds().intersects(jLabel16.getBounds())||filip.getBounds().intersects(jLabel17.getBounds())){
            } else {
                y=y+4;
                filip.setLocation(x, y);
            }

            try {
                t1.sleep(1000/FPS);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
            }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filip = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/Untitled-4.png"))); // NOI18N
        filip.setText("jLabel5");
        getContentPane().add(filip, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/pixil-frame-0 (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 60, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/pixil-frame-0 (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 60));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/pixil-frame-0 (2).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 60, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 60, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 60, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 610, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 60, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 60, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 60, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 60, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 60, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 60, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 60, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 60, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/openthedoor.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 70, 120));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/kockica.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 60, -1));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 20, 120));

        setSize(new java.awt.Dimension(606, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new okno1().setVisible(true);
            }
        });
    }   
    
    
    
    
public void keyReleased(KeyEvent k) {
    }

    public void keyTyped(KeyEvent k) {
    }

    public void keyPressed(KeyEvent evt) {
        if (!(filip.getBounds().intersects(jLabel6.getBounds()))&&!(filip.getBounds().intersects(jLabel10.getBounds()))&&!(filip.getBounds().intersects(jLabel13.getBounds()))&&!(filip.getBounds().intersects(jLabel14.getBounds()))&&!(filip.getBounds().intersects(jLabel15.getBounds()))){
switch (evt.getKeyCode()) {
            case KeyEvent.VK_UP:
                y=y-10;
                filip.setLocation(x, y);
                break;
            case KeyEvent.VK_LEFT:
                x=x-5;
                filip.setLocation(x, y);
                filip.setIcon(new ImageIcon(getClass().getResource("../slike/livafilip.png")));
                break;
            case KeyEvent.VK_RIGHT:
                x=x+5;
                filip.setLocation(x, y);
                filip.setIcon(new ImageIcon(getClass().getResource("../slike/Untitled-4.png")));
                break;
        }
    }
        else {
            new zgubusiL().setVisible(true);
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel filip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
